spring.application.name=Shopping-Application


server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.format_sql=true